version: '3.2'
services:
  backend1:
      build: ./webapp
      tty: true
      volumes:
        - './webapp/src:/backend-dir-inside-container'

  backend2:
      build: ./webapp
      tty: true
      volumes:
        - './webapp/src:/backend-dir-inside-container'

  backend3:
      build: ./webapp
      tty: true
      volumes:
        - './webapp/src:/backend-dir-inside-container'

  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - backend1
          - backend2
          - backend3
      ports:
          - '8080:8080'

volumes:
  webapp:
